/**
 * Main hook for loading and managing the models dataset.
 * Provides access to all models and their multilingual content.
 */

import { useState, useEffect } from 'react';
import { FashionModel, ModelsDataset } from '../types/model';

interface UseModelsReturn {
  /** All loaded models */
  models: FashionModel[];
  
  /** Languages available in the dataset */
  languages: string[];
  
  /** Whether data is still loading */
  isLoading: boolean;
  
  /** Error message if loading failed */
  error: string | null;
  
  /** Get a model by ID */
  getModelById: (id: number) => FashionModel | undefined;
  
  /** Search models by name */
  searchModels: (query: string) => FashionModel[];
}

/**
 * Hook to load and manage models dataset.
 * 
 * Loads from src/data/models.json generated by process_csv.py
 * 
 * @returns Object with models, languages, loading state, and utility functions
 */
export const useModels = (): UseModelsReturn => {
  const [models, setModels] = useState<FashionModel[]>([]);
  const [languages, setLanguages] = useState<string[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const loadModels = async () => {
      try {
        setIsLoading(true);
        setError(null);

        const response = await fetch('/data/models.json');
        if (!response.ok) {
          throw new Error(`Failed to load models: ${response.statusText}`);
        }

        const dataset: ModelsDataset = await response.json();
        setModels(dataset.models);
        setLanguages(dataset.languages);
      } catch (err) {
        const message =
          err instanceof Error
            ? err.message
            : 'Failed to load models dataset';
        setError(message);
        console.error('Error loading models:', err);
      } finally {
        setIsLoading(false);
      }
    };

    loadModels();
  }, []);

  const getModelById = (id: number): FashionModel | undefined => {
    return models.find((model) => model.id === id);
  };

  const searchModels = (query: string): FashionModel[] => {
    const lowerQuery = query.toLowerCase();
    return models.filter(
      (model) =>
        model.name.toLowerCase().includes(lowerQuery) ||
        Object.values(model.descriptions).some((desc) =>
          desc.toLowerCase().includes(lowerQuery)
        )
    );
  };

  return {
    models,
    languages,
    isLoading,
    error,
    getModelById,
    searchModels,
  };
};

export default useModels;
